services:
  vite-frontend:
    build: .
    ports:
      - "5173:5173"
    restart: always
    env_file:
      - .env
    networks:
      - localnet
    stdin_open: true
    tty: true

networks:
  localnet:
    driver: bridge